import {test,expect} from '@playwright/test';
test('content API returns seven aligned verses and rejects unavailable chapters',async({request})=>{
 const res=await request.get('/api/v1/chapters/1');expect(res.ok()).toBeTruthy();const {data}=await res.json();expect(data.verses).toHaveLength(7);expect(data.source.editions.map((e:{identifier:string})=>e.identifier)).toEqual(['quran-uthmani','en.pickthall','ur.jalandhry']);for(let i=0;i<7;i++){expect(data.verses[i].key).toBe(`1:${i+1}`);expect(data.verses[i].urdu).toBeTruthy();expect(data.verses[i].arabic).toBeTruthy()};expect((await request.get('/api/v1/chapters/2')).status()).toBe(404);
});
test('reader preferences, bookmarks and RTL survive reload',async({page})=>{
 await page.goto('/surah/1');await expect(page.locator('article')).toHaveCount(7);await page.getByRole('button',{name:'Bookmark ayah 2',exact:true}).click();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'sepia',exact:true}).click();await page.getByRole('button',{name:'Close settings'}).click();await page.reload();await expect(page.locator('.app')).toHaveClass(/theme-sepia/);await expect(page.getByRole('button',{name:'Bookmark ayah 2',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Reading',exact:true}).click();await expect(page.locator('.translations')).toHaveCount(0);await page.getByRole('button',{name:'اردو',exact:true}).click();await expect(page.locator('.app')).toHaveAttribute('dir','rtl');await page.screenshot({path:'/tmp/wahee-desktop.png',fullPage:true});
});
test('mobile has no overflow and navigation jumps to verse',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/surah/1');await page.evaluate(()=>document.fonts.ready);await expect(page.locator('article')).toHaveCount(7);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('tab',{name:'Verse',exact:true}).click();await page.locator('.navigation-list').getByRole('button',{name:/7 Ayah 1:7/}).click();await expect(page.locator('.sidebar')).not.toHaveClass(/mobile-open/);await page.screenshot({path:'/tmp/wahee-mobile.png',fullPage:true});
});
test('tafsir sources cover each verse with sanitized commentary',async({request})=>{
 for(const id of [169,160]) for(let n=1;n<=7;n++){
  const response=await request.get(`/api/v1/tafsirs/${id}/verses/1:${n}`);expect(response.ok()).toBeTruthy();const {data}=await response.json();expect(data.coveredVerses).toContain(`1:${n}`);expect(data.html.length).toBeGreaterThan(50);expect(data.html).not.toMatch(/<script|style=|onerror=/i);
 }
 expect((await request.get('/api/v1/tafsirs/169/verses/2:1')).status()).toBe(404);
});
test('tafsir supports language switching, navigation, escape and focus restoration',async({page})=>{
 await page.goto('/surah/1');const trigger=page.getByRole('button',{name:'Tafsir ayah 2',exact:true});await trigger.click();const panel=page.getByRole('dialog');await expect(panel).toBeVisible();await expect(panel.locator('.tafsir-prose')).not.toBeEmpty();await panel.getByLabel('Tafsir language').selectOption('urdu');await expect(panel.locator('.tafsir-prose')).toHaveAttribute('lang','ur');await panel.getByRole('button',{name:'Next',exact:true}).click();await expect(panel.locator('.tafsir-navigation')).toContainText('3 / 7');await expect(panel.locator('.tafsir-prose')).not.toBeEmpty();await page.screenshot({path:'/tmp/wahee-tafsir-desktop.png'});await page.keyboard.press('Escape');await expect(panel).toHaveCount(0);await expect(trigger).toBeFocused();
});
test('mobile tafsir is readable and handles a failed request',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/surah/1');await page.route('**/api/v1/tafsirs/**',route=>route.fulfill({status:503,body:'unavailable'}));await page.getByRole('button',{name:'Tafsir ayah 1',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('couldn’t load');await page.unroute('**/api/v1/tafsirs/**');await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.locator('.tafsir-prose')).not.toBeEmpty();await page.evaluate(()=>document.fonts.ready);expect(await page.locator('.tafsir-scroll').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBeTruthy();await page.screenshot({path:'/tmp/wahee-tafsir-mobile.png'});await page.getByRole('button',{name:'Close tafsir'}).click();await expect(page.locator('article')).toHaveCount(7);
});
