'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,X} from 'lucide-react';
import type {Chapter} from '../data/fatiha';
import type {TafsirPassage} from '../data/tafsir';
export default function TafsirPanel({ayah,chapter,locale,onChange,onClose}:{ayah:number;chapter:Chapter;locale:string;onChange:(n:number)=>void;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),body=useRef<HTMLDivElement>(null);
 const [language,setLanguage]=useState(locale==='ur'?'urdu':'english'),[passage,setPassage]=useState<TafsirPassage|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const ur=locale==='ur';const t=(en:string,u:string)=>ur?u:en;
 useEffect(()=>{const el=dialog.current;const before=document.body.style.overflow;el?.showModal();document.body.style.overflow='hidden';return()=>{el?.close();document.body.style.overflow=before}},[]);
 useEffect(()=>{const controller=new AbortController();setPassage(null);setError(false);body.current?.scrollTo(0,0);
 fetch(`/api/v1/tafsirs/${language==='urdu'?160:169}/verses/1:${ayah}`,{signal:controller.signal}).then(async res=>{if(!res.ok)throw new Error('Unavailable');return res.json()}).then(({data})=>{if(!controller.signal.aborted)setPassage(data)}).catch(()=>{if(!controller.signal.aborted)setError(true)});
 return()=>controller.abort();},[ayah,language,retry]);
 return <dialog ref={dialog} className="tafsir-dialog" aria-labelledby="tafsir-title" onCancel={onClose} onClick={e=>{if(e.target===dialog.current)onClose()}}><div className="tafsir-shell"><header className="tafsir-header"><div><div className="eyebrow">{t('UNDERSTAND THE AYAH','آیت کو سمجھیں')}</div><h2 id="tafsir-title">{t('Tafsir · Al-Fatihah','تفسیر · الفاتحہ')}</h2></div><button className="icon-button" aria-label="Close tafsir" onClick={onClose} autoFocus><X size={20}/></button></header><div className="tafsir-selectors"><label htmlFor="tafsir-language">{t('Tafsir language','تفسیر کی زبان')}</label><select id="tafsir-language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="english">English · Ibn Kathir (Abridged)</option><option value="urdu">اردو · تفسیر ابن کثیر</option></select></div><div className="tafsir-scroll" ref={body}><div className="tafsir-verse"><span>1:{ayah}</span><p className="arabic" lang="ar" dir="rtl">{chapter.verses[ayah-1].arabic}</p></div>{!passage&&!error&&<p className="tafsir-status" role="status">{t('Loading tafsir…','تفسیر لوڈ ہو رہی ہے…')}</p>}{error&&<div className="tafsir-status" role="alert"><p>{t('We couldn’t load this tafsir. Please try again.','تفسیر لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔')}</p><button onClick={()=>setRetry(n=>n+1)}>{t('Try again','دوبارہ کوشش کریں')}</button></div>}{passage&&<><div className="tafsir-attribution"><strong>{passage.resource.name}</strong><span>{passage.resource.author}</span><span>{t('Commentary for','تفسیر برائے')} {passage.coveredVerses.join(', ')}</span><a href={passage.sourceUrl} target="_blank" rel="noreferrer">{t('Read source on Quran.com','Quran.com پر ماخذ پڑھیں')}<ArrowUpRight size={13}/></a></div><div className={`tafsir-prose ${language==='urdu'?'tafsir-urdu':''}`} dir={language==='urdu'?'rtl':'ltr'} lang={language==='urdu'?'ur':'en'} dangerouslySetInnerHTML={{__html:passage.html}}/></>}</div><footer className="tafsir-navigation"><button disabled={ayah===1} onClick={()=>onChange(ayah-1)}><ChevronLeft size={16}/>{t('Previous','پچھلی')}</button><span>{t('Ayah','آیت')} {ayah} / 7</span><button disabled={ayah===7} onClick={()=>onChange(ayah+1)}>{t('Next','اگلی')}<ChevronRight size={16}/></button></footer></div></dialog>
}
